FROM   debian:latest

RUN    apt-get update && apt-get upgrade -y

RUN    apt-get install -y nginx

COPY   ./index.html /usr/share/nginx/html

COPY   ./conf/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE  8080

CMD    ["nginx", "-g", "daemon off;"]