services:
  engine-x:
    build: ./nginx
    container_name: engine-x
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - ./nginx:/usr/share/nginx/html
    networks:
      - my-network

  wordpress:
    build: ./wordpress
    container_name: wordpress
    ports:
      - "3000:3000"
    networks:
      - my-network

  db:
    build: ./mariaDB
    env_file:
      - .env
    container_name: db
    ports:
      - "3306:3306"
    networks:
      - my-network


  networks:
    my-network:
      name: docker-network