version: '3.3'

services:
  engine-x:
    build: ./nginx
    container_name: engine-x
    ports:
      - "8080:8080"
    volumes:
      - ./test:/usr/share/nginx/html


  wordpress:
    build: ./wordpress
    container_name: wordpress
    ports:
      - "3000:3000"
    depends_on:
      - engine-x




  # db:
  #   build: ./mariaDB
  #   container_name: db
  #   ports:
  #     - "3306:3306"