version: '3.3'

services:
  engine-x:
    build: ./nginx
    container_name: engine-x
    ports:
      - "8080:8080"
    volumes:
      - ./test:/usr/share/nginx/html

  db:
    build: ./mariaDB
    container_name: db
    ports:
      - "3306:3306"