services:
  engine-x:
    build: ./nginx
    container_name: engine-x
    ports:
      - "8080:8080"
    depends_on:
      - wordpress
    volumes:
      - ./nginx:/usr/share/nginx/html

  wordpress:
    build: ./wordpress
    container_name: wordpress
    ports:
      - "3000:3000"






  # db:
  #   build: ./mariaDB
  #   container_name: db
  #   ports:
  #     - "3306:3306"