mysql << EOF
CREATE DATABASE IF NOT EXISTS $SQL_DB_NAME;
CREATE USER IF NOT EXISTS '$SQL_USERNAME'@'%' IDENTIFIED BY '$SQL_PASSWORD';
GRANT ALL PRIVILEGES ON mydb.* TO '$SQL_USERNAME'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'$SQL_HOST' IDENTIFIED BY '$SQL_ROOT_PASSWORD';
EOF